config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # データの新規作成フォームを表示するアクション
  # def new
  #   @book = Book.new
  # end

  # データを追加（保存）するアクション
  def create
    @books = Book.all
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  # データを追加（保存）するアクション
  def index
    @books = Book.all
    @book = Book.new
  end

  # データの内容（詳細）を表示するアクション
  def show
    @book = Book.find(params[:id])
  end

  # データを更新するためのフォームを表示するアクション
  def edit
    @book = Book.find(params[:id])
  end

  # データを更新するアクション
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  # データを削除するアクション
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<!--  データを更新するためのフォームを表示  -->
<h1>Editing Book</h1>

<!--  バリデーションによるエラーメッセージ  -->
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <% @book.errors.each do |attribute,message| %>
    <%= @book.errors.full_message(attribute, message) %>
  <% end %>
<% end %>

<%= form_with model: @book, url: book_path(@book) do |f| %>

  <div class="field">
    <label>Title</label>
    <div><%= f.text_field :title %></div>
  </div>

  <div class="field">
    <label>Body</label>
    <div><%= f.text_area :body %></div>
  </div>

  <div class="field">
    <%= f.submit 'Update Book' %>
  </div>
<% end %>


<!--  詳細ボタン  -->
<%= link_to 'Show', book_path %>
<span>|</span>
<!--  戻るボタン  -->
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<!--  投稿一覧ページ  -->

<body>
  <h1>Books</h1>
  <table>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th>
    </tr>

    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to 'Show', book_path(book) %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book_path(book), method: :delete, "data-confirm" => "Are you sure?" %></td>
    　</tr>
    <% end %>
  </table>

  <!--  新規投稿表示  -->
  <h1>New book</h1>
  <!--  バリデーションによるエラーメッセージ  -->
  <% if @book.errors.any? %>
    <%= @book.errors.count %> errors prohibited this book from being saved:
    <% @book.errors.each do |attribute,message| %>
      <%= @book.errors.full_message(attribute, message) %>
    <% end %>
  <% end %>


  <%= form_with model: @book, url: books_path, local:true do |f| %>

    <!--  Title  -->
    <div class="field">
      <label>Title</label>
      <div><%= f.text_field :title %></div>
    </div>


    <!--  Body  -->
    <div class="field">
      <label>Body</label>
      <div><%= f.text_area :body %></div>
    </div>


    <!--  投稿ボタン  -->
    <div class="field">
      <%= f.submit 'Create Book' %>
    </div>

  <% end %>
</body>

app/views/books/show.html.erb
<!--  投稿詳細ページを表示  -->

<!--  フラッシュメッセージ  -->
<div class="flash">
  <%= flash[:notice] %>
  <%= flash[:success] %>
</div>

<p><strong>Title:</strong><%= @book.title %></p>

<p><strong>Body:</strong><%= @book.body %></p>

<!--  編集ボタン  -->
<%= link_to 'Edit', edit_book_path(@book) %>
<span>|</span>
<!--  戻るボタン  -->
<%= link_to 'Back', books_path %>

app/views/homes/top.html.erb
<body>
  <h1>ようこそ Bookers へ！</h1>
  <p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
  <p>印象を共有し交換することができます</p>
  <!-- startボタン -->
  <p><%= link_to "start", books_path %></p>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>